services:
  ttmm_api:
    build:
      args:
        user: ttmm_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ttmm_api
    container_name: ttmm_api
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - ttmm_nw

  db:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    container_name: ttmm_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
     - 3306:3306
    networks:
      - ttmm_nw

  nginx:
    image: nginx:stable-alpine
    container_name: ttmm_api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx/ttmm-http.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ttmm_nw

networks:
  ttmm_nw:
    name: ttmm_network
    driver: bridge
    external: true