services:
  ttmm_api:
    build:
      args:
        user: ttmm_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ttmm_api
    container_name: ttmm_api
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - ttmm_nw

  nginx:
    image: nginx:stable-alpine
    container_name: ttmm_api-nginx
    restart: unless-stopped
    ports:
      - 8000:443
    volumes:
      - ./:/var/www/ttmm
      - ./docker-compose/nginx/ttmm-https.conf:/etc/nginx/conf.d/ttmm.conf
      - ./docker-compose/nginx/snippets/:/etc/nginx/snippets/
      - ../certbot/conf/archive/${DOMAIN}/:/etc/nginx/ssl/${DOMAIN}/
    networks:
      - ttmm_nw

networks:
  ttmm_nw:
    name: ttmm_network
    driver: bridge
    external: true